### ISSUE TITLE
DC-1 not working in Live 9.7 ??

### ISSUE THREAD

**Issue by lkjts** [mpiraux/CMD-DC-1-Ableton-9-Control-Surface-Script#9]
I've previously set up DC-1 to work as expected in Live 9.2, but recently i updated to live 9.7 and now DC-1 does not appear in control surfaces list any more. 

Is there any way to fix this please?

[Log.txt](https://github.com/mpiraux/CMD-DC-1-Ableton-9-Control-Surface-Script/files/1076661/Log.txt)

**Comment by mpiraux** [comment]
```
873 ms. RemoteScriptError: Traceback (most recent call last):

873 ms. RemoteScriptError:   File "<string>", line 1, in <module>

873 ms. RemoteScriptError:   File "/Applications/Ableton Live 9 Suite.app/Contents/App-Resources/MIDI Remote Scripts/CMD_DC1/__init__.py", line 3, in <module>

873 ms. RemoteScriptError:     
873 ms. RemoteScriptError: from DC1 import DC1

873 ms. RemoteScriptError:   File "/Applications/Ableton Live 9 Suite.app/Contents/App-Resources/MIDI Remote Scripts/CMD_DC1/DC1.py", line 32, in <module>

873 ms. RemoteScriptError:     
873 ms. RemoteScriptError: from _Framework.TrackEQComponent import TrackEQComponent # Class representing a track's EQ, it attaches to the last EQ device in the track

873 ms. RemoteScriptError: ImportError
873 ms. RemoteScriptError: : 
873 ms. RemoteScriptError: No module named TrackEQComponent
873 ms. RemoteScriptError:
```
The API seems to have effectively changed. Unfortunately, as Ableton does not provides open documentation about their internal API, it makes tracking this change very tedious. At the moment, I do not own a recent version of Ableton and I am not using the program actively, nor am I interested into it anymore. All those facts combined makes fixing this issue anytime soon not possible. Feel free to tinker with it if you have the knowledge and come back with your findings though ;)
